name: sqlite_storage
description: Common helpers for SQLite
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cachecontrol: ^0.0.1
  http: ^1.2.0
  # query: ^2.1.0
  mime: ^1.0.5
  path: ^1.9.0
  shortid: ^0.1.2
  sqlite_async: ^0.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.25.2
