name: sqlite_storage
description: Common SQLite storage interfaces for Drift
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.16.0
  path_provider: ^2.0.0
  path: ^1.9.0
  uuid: ^4.3.3
  mime: ^1.0.5
  http: ^1.2.1
  cachecontrol: ^0.0.1
  crypto: ^3.0.3

dev_dependencies:
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
