name: example
description: SQLite storage helpers example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.6.0
  path_provider: ^2.1.2
  sqlite_storage:
    path: ../packages/sqlite_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
