name: example
description: SQLite storage helpers example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  drift: ^2.16.0
  sqlite_storage:
    path: ../packages/sqlite_storage
  path: ^1.9.0
  sqlite3: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
