name: sqlite_storage_pocketbase
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  fetch_client: ^1.0.2
  http: ^1.2.1
  pocketbase: ^0.18.1
  sqlite_storage:
    path: ../sqlite_storage

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.25.2

