name: sqlite_storage_extension
description: SQLite inspector
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  devtools_extensions: ^0.0.9
  signals: ^4.4.0
  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  dev: flutter run -d chrome --dart-define=use_simulated_environment=true
  build: dart run devtools_extensions build_and_copy --source=. --dest=../sqlite_storage/extension/devtools
