name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqlite_storage_pocketbase:
    path: ../
  sqlite_storage:
    path: ../../sqlite_storage
  pocketbase: ^0.18.1
  drift: ^2.16.0
  sqlite3: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.2
  fetch_client: ^1.0.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
